import { SessionItem, TaskItem, ProviderConfig } from './types';

export const INITIAL_PROVIDERS: ProviderConfig[] = [
  {
    id: 'prov-openai',
    name: 'openai',
    type: 'openai',
    upstreamUrl: 'https://api.openai.com/v1',
    apiKey: 'sk-proj-live-token-secret-openai',
    proxy: 'http://127.0.0.1:7890',
    modelRoutes: 'gpt-4o, gpt-4o-mini, o1, o3-mini',
    isActive: true,
  },
  {
    id: 'prov-deepseek',
    name: 'deepseek',
    type: 'openai',
    upstreamUrl: 'https://api.deepseek.com/v1',
    apiKey: 'sk-deepseek-live-production-key',
    proxy: '',
    modelRoutes: 'deepseek-chat, deepseek-coder, deepseek-reasoner',
    isActive: true,
  },
  {
    id: 'prov-sensenova',
    name: 'sensenova',
    type: 'openai',
    upstreamUrl: 'https://token.sensenova.cn/v1',
    apiKey: 'sk-sense-token-enterprise',
    proxy: '',
    modelRoutes: 'sensenova-*, nova-*',
    isActive: true,
  },
  {
    id: 'prov-bigmodel',
    name: 'bigmodel',
    type: 'openai',
    upstreamUrl: 'https://open.bigmodel.cn/api/paas/v4',
    apiKey: 'sk-glm-auth-token-example',
    proxy: '',
    modelRoutes: 'glm-*, codegeex-*',
    isActive: true,
  },
];

export const INITIAL_SESSIONS: SessionItem[] = [
  {
    id: 'sess-3',
    sessionNum: 3,
    taskCount: 2,
    requestCount: 3,
    successRequestCount: 3,
    title: '分析 Python 异步网关转发与连接池复用方案',
    provider: 'deepseek',
    inputTokens: 92,
    outputTokens: 60,
    totalTokens: 152,
    cacheHitRate: 71.7,
    cacheHitTokens: 66,
    model: 'deepseek-coder',
    costCny: 0.012,
    savedCny: 0.038,
    createdAt: '2026-09-02 22:40:15',
    userPromptSnippet: '如何在 httpx.AsyncClient 中保持长连接复用并避免在长时间高并发代理场景下的连接泄漏？',
    requests: [
      {
        id: 'req-3-2',
        requestId: 2,
        time: '22:41:02',
        model: 'deepseek-coder',
        provider: 'deepseek',
        inputTokens: 48,
        outputTokens: 32,
        totalTokens: 80,
        cacheHitTokens: 36,
        cacheHitRate: 75.0,
        ttftMs: 230,
        durationMs: 980,
        costCny: 0.006,
        savedCny: 0.021,
        promptSnippet: '如何在 httpx.AsyncClient 中保持长连接复用并避免连接泄漏？',
        responseSnippet: '使用全局单例 AsyncClient 并配合 app.lifespan 管理生命周期，设置合理的 keepalive 阈值...',
      },
      {
        id: 'req-3-1',
        requestId: 1,
        time: '22:40:15',
        model: 'deepseek-coder',
        provider: 'deepseek',
        inputTokens: 44,
        outputTokens: 28,
        totalTokens: 72,
        cacheHitTokens: 30,
        cacheHitRate: 68.2,
        ttftMs: 310,
        durationMs: 840,
        costCny: 0.006,
        savedCny: 0.017,
        promptSnippet: '帮我设计一个基于 FastAPI 的极简用量网关架构...',
        responseSnippet: '核心结构建议分为 Router 路由层、Proxy 转发层与 UsageTracker 计数层...',
      },
    ],
  },
  {
    id: 'sess-2',
    sessionNum: 2,
    taskCount: 1,
    requestCount: 2,
    successRequestCount: 2,
    title: '重构首会话截断标题提取与状态缓存',
    provider: 'sensenova',
    inputTokens: 30,
    outputTokens: 40,
    totalTokens: 70,
    cacheHitRate: 80.0,
    cacheHitTokens: 24,
    model: 'sensenova-v5-pro',
    costCny: 0.004,
    savedCny: 0.018,
    createdAt: '2026-09-02 21:15:30',
    userPromptSnippet: '在悬浮条上展示当前会话标题时，如何提取首个 user message 并做优雅省略截断？',
    requests: [
      {
        id: 'req-2-2',
        requestId: 2,
        time: '21:16:10',
        model: 'sensenova-v5-pro',
        provider: 'sensenova',
        inputTokens: 16,
        outputTokens: 22,
        totalTokens: 38,
        cacheHitTokens: 13,
        cacheHitRate: 81.2,
        ttftMs: 190,
        durationMs: 620,
        costCny: 0.002,
        savedCny: 0.010,
        promptSnippet: '提取 messages[0] 或第一条 user 提示词前 18 个字符并加省略号...',
        responseSnippet: 'def extract_truncated_title(messages, max_len=20): ...',
      },
      {
        id: 'req-2-1',
        requestId: 1,
        time: '21:15:30',
        model: 'sensenova-v5-pro',
        provider: 'sensenova',
        inputTokens: 14,
        outputTokens: 18,
        totalTokens: 32,
        cacheHitTokens: 11,
        cacheHitRate: 78.6,
        ttftMs: 240,
        durationMs: 580,
        costCny: 0.002,
        savedCny: 0.008,
        promptSnippet: '在悬浮条上展示当前会话标题时，如何做弹性文本截断？',
        responseSnippet: '可以使用 CSS text-overflow: ellipsis 配合最大宽度，或后端预截断...',
      },
    ],
  },
  {
    id: 'sess-1',
    sessionNum: 1,
    taskCount: 2,
    requestCount: 4,
    successRequestCount: 4,
    title: 'IDE 插件流式接口 stream_options 兼容处理',
    provider: 'bigmodel',
    inputTokens: 196,
    outputTokens: 80,
    totalTokens: 276,
    cacheHitRate: 78.6,
    cacheHitTokens: 154,
    model: 'glm-4-flash',
    costCny: 0.016,
    savedCny: 0.065,
    createdAt: '2026-09-02 20:04:12',
    userPromptSnippet: '验证各大模型厂商（智谱GLM / DeepSeek）在流式结束帧返回的 prompt_tokens 格式',
    requests: [
      {
        id: 'req-1-4',
        requestId: 4,
        time: '20:10:45',
        model: 'glm-4-flash',
        provider: 'bigmodel',
        inputTokens: 62,
        outputTokens: 25,
        totalTokens: 87,
        cacheHitTokens: 50,
        cacheHitRate: 80.6,
        ttftMs: 210,
        durationMs: 760,
        costCny: 0.005,
        savedCny: 0.022,
        promptSnippet: '验证 deepseek-chat 在流式结束帧返回的 prompt_tokens 细节',
        responseSnippet: '在 include_usage: true 时，最终帧包含完整 usage 字典...',
      },
    ],
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'turn-5',
    taskNum: 5,
    name: 'OpenAI o3-mini 推理思考流流式 usage 解析与统计',
    sessionId: 'sess-4',
    sessionNum: 4,
    requestCount: 1,
    successRequestCount: 1,
    provider: 'openai',
    inputTokens: 120,
    outputTokens: 45,
    totalTokens: 165,
    cacheHitRate: 82.5,
    cacheHitTokens: 99,
    model: 'o3-mini',
    costCny: 0.018,
    savedCny: 0.052,
    ttftMs: 180,
    createdAt: '2026-09-02 22:50:00',
    userPromptSnippet: '请解析 OpenAI o3-mini 在启用 reasoning_effort 时的 completion_tokens_details 与 prompt 缓存计费规则',
    requests: [],
  },
  {
    id: 'turn-4',
    taskNum: 4,
    name: '连接池复用与跨平台 macOS 异常规避',
    sessionId: 'sess-3',
    sessionNum: 3,
    requestCount: 2,
    successRequestCount: 2,
    provider: 'deepseek',
    inputTokens: 48,
    outputTokens: 32,
    totalTokens: 80,
    cacheHitRate: 75.0,
    cacheHitTokens: 36,
    model: 'deepseek-coder',
    costCny: 0.006,
    savedCny: 0.021,
    ttftMs: 230,
    createdAt: '2026-09-02 22:41:02',
    userPromptSnippet: '如何在 httpx.AsyncClient 中保持长连接复用并避免在 macOS 平台下的 Tcl 属性报错？',
    requests: [
      {
        id: 'req-3-2',
        requestId: 2,
        time: '22:41:02',
        model: 'deepseek-coder',
        provider: 'deepseek',
        inputTokens: 48,
        outputTokens: 32,
        totalTokens: 80,
        cacheHitTokens: 36,
        cacheHitRate: 75.0,
        ttftMs: 230,
        durationMs: 980,
        costCny: 0.006,
        savedCny: 0.021,
        promptSnippet: '如何在 httpx.AsyncClient 中保持长连接复用并避免连接泄漏？',
        responseSnippet: '使用全局单例 AsyncClient 并配合 app.lifespan 管理生命周期...',
      },
    ],
  },
  {
    id: 'turn-3',
    taskNum: 3,
    name: '极简用量网关架构与模型通配路由',
    sessionId: 'sess-3',
    sessionNum: 3,
    requestCount: 1,
    successRequestCount: 1,
    provider: 'deepseek',
    inputTokens: 44,
    outputTokens: 28,
    totalTokens: 72,
    cacheHitRate: 68.2,
    cacheHitTokens: 30,
    model: 'deepseek-coder',
    costCny: 0.006,
    savedCny: 0.017,
    ttftMs: 310,
    createdAt: '2026-09-02 22:40:15',
    userPromptSnippet: '帮我设计一个基于 FastAPI 的极简用量网关架构，支持 models 通配路由',
    requests: [],
  },
  {
    id: 'turn-2',
    taskNum: 2,
    name: '商汤 SenseNova 接口首指令标题提取算法',
    sessionId: 'sess-2',
    sessionNum: 2,
    requestCount: 2,
    successRequestCount: 2,
    provider: 'sensenova',
    inputTokens: 30,
    outputTokens: 40,
    totalTokens: 70,
    cacheHitRate: 80.0,
    cacheHitTokens: 24,
    model: 'sensenova-v5-pro',
    costCny: 0.004,
    savedCny: 0.018,
    ttftMs: 190,
    createdAt: '2026-09-02 21:15:30',
    userPromptSnippet: '提取 messages[0] 或第一条 user 提示词前 18 个字符并加省略号，支持过滤 Markdown 标记',
    requests: [],
  },
  {
    id: 'turn-1',
    taskNum: 1,
    name: '智谱 GLM 流式结束帧 Usage 数据透传与合算',
    sessionId: 'sess-1',
    sessionNum: 1,
    requestCount: 4,
    successRequestCount: 4,
    provider: 'bigmodel',
    inputTokens: 196,
    outputTokens: 80,
    totalTokens: 276,
    cacheHitRate: 78.6,
    cacheHitTokens: 154,
    model: 'glm-4-flash',
    costCny: 0.016,
    savedCny: 0.065,
    ttftMs: 210,
    createdAt: '2026-09-02 20:04:12',
    userPromptSnippet: '验证智谱开放平台 glm-4-flash 接口在 stream 模式下的 usage 注入细节',
    requests: [],
  },
];
